[INFO] - 2022-03-30 09:56:52,952 :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.23:5000 (Press CTRL+C to quit) in _internal:224
[INFO] - 2022-03-30 09:56:53,281 : 172.18.0.1 - - [30/Mar/2022 09:56:53] "GET / HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 09:57:11,983 : 172.18.0.1 - - [30/Mar/2022 09:57:11] "GET / HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 09:58:43,338 : 172.18.0.1 - - [30/Mar/2022 09:58:43] "GET /summary HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 10:11:04,455 :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.23:5000 (Press CTRL+C to quit) in _internal:224
[INFO] - 2022-03-30 10:11:12,723 : 172.18.0.1 - - [30/Mar/2022 10:11:12] "GET / HTTP/1.1" 200 - in _internal:224
[ERROR] - 2022-03-30 10:11:27,168 : Exception on /summary [GET] in app:1455
Traceback (most recent call last):
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "main.py", line 26, in serve_summary
    json_template = json.load(open("templates/summary.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'templates/summary.json'
[INFO] - 2022-03-30 10:11:27,170 : 172.18.0.1 - - [30/Mar/2022 10:11:27] "[35m[1mGET /summary HTTP/1.1[0m" 500 - in _internal:224
[ERROR] - 2022-03-30 10:11:33,950 : Exception on /summary [GET] in app:1455
Traceback (most recent call last):
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "main.py", line 26, in serve_summary
    json_template = json.load(open("templates/summary.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'templates/summary.json'
[INFO] - 2022-03-30 10:11:33,951 : 172.18.0.1 - - [30/Mar/2022 10:11:33] "[35m[1mGET /summary HTTP/1.1[0m" 500 - in _internal:224
[INFO] - 2022-03-30 10:11:37,859 : 172.18.0.1 - - [30/Mar/2022 10:11:37] "GET / HTTP/1.1" 200 - in _internal:224
[ERROR] - 2022-03-30 10:11:42,236 : Exception on /summary [GET] in app:1455
Traceback (most recent call last):
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/COVID-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "main.py", line 26, in serve_summary
    json_template = json.load(open("templates/summary.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'templates/summary.json'
[INFO] - 2022-03-30 10:11:42,237 : 172.18.0.1 - - [30/Mar/2022 10:11:42] "[35m[1mGET /summary HTTP/1.1[0m" 500 - in _internal:224
[INFO] - 2022-03-30 10:18:10,183 :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.15:5000 (Press CTRL+C to quit) in _internal:224
[INFO] - 2022-03-30 10:18:10,436 : 172.18.0.1 - - [30/Mar/2022 10:18:10] "GET / HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 10:18:10,808 : 172.18.0.1 - - [30/Mar/2022 10:18:10] "GET / HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 10:18:11,953 : 172.18.0.1 - - [30/Mar/2022 10:18:11] "GET /summary HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 10:20:15,078 : 172.18.0.1 - - [30/Mar/2022 10:20:15] "[36mGET / HTTP/1.1[0m" 304 - in _internal:224
[INFO] - 2022-03-30 10:20:16,406 : 172.18.0.1 - - [30/Mar/2022 10:20:16] "GET /summary HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 10:20:30,032 : 172.18.0.1 - - [30/Mar/2022 10:20:30] "GET / HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 10:20:30,953 : 172.18.0.1 - - [30/Mar/2022 10:20:30] "GET /summary HTTP/1.1" 200 - in _internal:224
[INFO] - 2022-03-30 10:20:34,306 : 172.18.0.1 - - [30/Mar/2022 10:20:34] "[36mGET / HTTP/1.1[0m" 304 - in _internal:224
[INFO] - 2022-03-30 10:20:35,191 : 172.18.0.1 - - [30/Mar/2022 10:20:35] "GET /summary HTTP/1.1" 200 - in _internal:224
